Gem::Specification.new do |s|
  s.name = 'execution_checker'
  s.version = '0.1.0'
  s.summary = 'Checks the execution of a script by checking the file ' +
      'modification date of the output file generated by the script.'
  s.authors = ['James Robertson']
  s.files = Dir['lib/execution_checker.rb']
  s.add_runtime_dependency('dynarex', '~> 1.7', '>=1.7.22')
  s.add_runtime_dependency('sps-pub', '~> 0.5', '>=0.5.5')
  s.signing_key = '../privatekeys/execution_checker.pem'
  s.cert_chain  = ['gem-public_cert.pem']
  s.license = 'MIT'
  s.email = 'james@jamesrobertson.eu'
  s.homepage = 'https://github.com/jrobertson/execution_checker'
end
